language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  
env:
  - GO111MODULE=auto

install: true
sudo: true
go_import_path: github.com/ochinchina/supervisord
before_install:
  - go get github.com/ochinchina/supervisord

script:
- go test ./...

after_script:
  - go get -v github.com/alecthomas/gometalinter/...
  - gometalinter --install
  - gometalinter

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
